"""Pydantic schemas for DeliveryLint pipeline contracts."""

from backend.app.schemas.common import AuthorityLevel
from backend.app.schemas.correction_ui import (
    CorrectionFindingView,
    CorrectionSourceSummary,
    CorrectionSummary,
    CorrectionTargetDocument,
    CorrectionUIInput,
    CorrectionUIResponse,
)
from backend.app.schemas.enums import (
    ClusterResolutionStatus,
    DateType,
    DependencyType,
    DocType,
    DocumentRole,
    FactCategory,
    FactPolarity,
    FactStatus,
    FactType,
    InferenceSource,
    LintFindingType,
    LintSeverity,
    Priority,
    ReliabilityFlag,
    ReviewPriority,
    RiskLevel,
    SourceOrigin,
    SourceStatus,
    TargetQualityFlag,
)
from backend.app.schemas.fact_cluster import FactCluster
from backend.app.schemas.fact_parser import (
    ExtractProjectFactsInput,
    ExtractProjectFactsOutput,
    FactExtractionWarning,
    FactExtractionWarningCode,
    FactParserDocument,
    ProjectFactLLMOutput,
    ProjectFactLLMResponse,
)
from backend.app.schemas.lint import (
    LintContext,
    LintEngineWarning,
    LintEngineWarningCode,
    LintFinding,
    RunLintInput,
    RunLintOutput,
)
from backend.app.schemas.pipeline import PipelineDebugContext, PipelineResult
from backend.app.schemas.project_fact import EvidenceSpan, ProjectFact, ProjectFactAttributes
from backend.app.schemas.source_profile import (
    DocumentMetadata,
    ProfileSourceArgs,
    ProfileSourceDocument,
    SourceProfile,
    SourceProfileInference,
    SourceProfileInput,
)
from backend.app.schemas.target_document import (
    TargetClaim,
    TargetLocation,
    TargetProfile,
    TargetSection,
)
from backend.app.schemas.target_parser import (
    ParseTargetDocumentInput,
    TargetClaimLLMOutput,
    TargetDocumentLLMResponse,
    TargetParseResult,
    TargetParseWarning,
    TargetParseWarningCode,
    TargetParserDocument,
    TargetSectionLLMOutput,
)

__all__ = [
    "AuthorityLevel",
    "ClusterResolutionStatus",
    "CorrectionFindingView",
    "CorrectionSourceSummary",
    "CorrectionSummary",
    "CorrectionTargetDocument",
    "CorrectionUIInput",
    "CorrectionUIResponse",
    "DateType",
    "DependencyType",
    "DocType",
    "DocumentMetadata",
    "DocumentRole",
    "EvidenceSpan",
    "ExtractProjectFactsInput",
    "ExtractProjectFactsOutput",
    "FactCategory",
    "FactCluster",
    "FactExtractionWarning",
    "FactExtractionWarningCode",
    "FactParserDocument",
    "FactPolarity",
    "FactStatus",
    "FactType",
    "InferenceSource",
    "LintContext",
    "LintEngineWarning",
    "LintEngineWarningCode",
    "LintFinding",
    "LintFindingType",
    "LintSeverity",
    "ParseTargetDocumentInput",
    "PipelineDebugContext",
    "PipelineResult",
    "Priority",
    "ProfileSourceArgs",
    "ProfileSourceDocument",
    "ProjectFact",
    "ProjectFactAttributes",
    "ProjectFactLLMOutput",
    "ProjectFactLLMResponse",
    "ReliabilityFlag",
    "ReviewPriority",
    "RiskLevel",
    "RunLintInput",
    "RunLintOutput",
    "SourceOrigin",
    "SourceProfile",
    "SourceProfileInference",
    "SourceProfileInput",
    "SourceStatus",
    "TargetClaim",
    "TargetClaimLLMOutput",
    "TargetDocumentLLMResponse",
    "TargetLocation",
    "TargetParseResult",
    "TargetParseWarning",
    "TargetParseWarningCode",
    "TargetParserDocument",
    "TargetProfile",
    "TargetQualityFlag",
    "TargetSection",
    "TargetSectionLLMOutput",
]
